### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by ghost** [vitech-team-sdlc/SDLC#5]
#1 #7 
- [x] Gather requirements
- [x] Gather list of solutions
- [x] Select the best fit

**Comment by ghost** [comment]
Discussed with @antonnazaruk . Trunk based will be used as standard

**Comment by ghost** [comment]
Analyzing  
https://www.toptal.com/software/trunk-based-development-git-flow
https://trunkbaseddevelopment.com/

**Comment by antonnazaruk** [comment]
According to https://www.amazon.com/Continuous-Delivery-Deployment-Automation-Addison-Wesley/dp/0321601912 and https://www.amazon.com/Accelerate-Software-Performing-Technology-Organizations/dp/1942788339 and many other books/articles - trunk-based approach is a prerequisite to **continuous delivery** capability. If there are no strong arguments against I'd like to select trunk-based as our approach.

**Comment by ghost** [comment]
Totally agreed with @antonnazaruk, let's proceed with trunk-based.
