### ISSUE TITLE
QG: Snyk alternative 

### ISSUE THREAD

**Issue by serhiykrupka** [vitech-team-sdlc/SDLC#90]
We need to find a more affordable or open-source solution for security check.

https://github.com/goodwithtech/dockle
https://github.com/aquasecurity/trivy

check also nice implementation fro Azure pipelines: https://github.com/Azure/container-scan

**Comment by antonnazaruk** [comment]
From @serhiy-krupka-vitech : need to consider free service - https://github.com/aquasecurity/trivy
